name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: 107.23.33.108        # ✅ use correct EC2 public IP (your new instance)
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "~/ci-cd-crash"

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 107.23.33.108
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/ci-cd-crash
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -a -q) || true
          docker build -t bhavya-app .
          docker run -d -p 3000:3000 --name bhavya-app bhavya-app
