name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@107.23.33.108 << 'EOF'
            cd ~/ci-cd-crash
            git pull origin main
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -a -q) || true
            docker rmi sonibhavya/bhavya-app || true
            docker pull sonibhavya/bhavya-app:latest
            docker run -d -p 3000:3000 --name bhavya-app sonibhavya/bhavya-app:latest
          EOF
